[behavior]
# When set to `true` the `managed` flag is always assumed to be `true`.
force-rye-managed = true

# Enables global shims when set to `true`.  This means that the installed
# `python` shim will resolve to a Rye-managed toolchain even outside of
# virtual environments.
global-python = false

# When set to `true`, Rye will use `uv` for package resolution and installation.
# Set to `false` to fall back to the `pip-tools` resolver.
# Learn more about uv here: https://github.com/astral-sh/uv
use-uv = true

# Enable or disable automatic `sync` after `add` and `remove`.  This defaults
# to `true` when uv is enabled and `false` otherwise.
autosync = true

# Marks the managed .venv in a way that cloud-based synchronization systems
# like Dropbox and iCloud Files will not upload it.  This defaults to `true`
# as a .venv in cloud storage typically does not make sense.  Set this to
# `false` to disable this behavior.
venv-mark-sync-ignore = true

# When set to `true` Rye will fetch certain interpreters with build information.
# This will increase the space requirements, will put the interpreter into an
# extra folder called `./install/` and place build artifacts adjacent in `./build`.
fetch-with-build-info = false

[proxy]
# the proxy to use for HTTP (overridden by the http_proxy environment variable)
http = "http://mtkdrone01.mediatek.inc:23984"
# the proxy to use for HTTPS (overridden by the https_proxy environment variable)
https = "http://mtkdrone01.mediatek.inc:23984"

# [[sources]]
# name = "default"
# url = "http://10.9.16.152/simple"
