# This action has been disabled since it is not frequently used.
# Just leave it for the sake of the example.

name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: write-all

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    permissions: write-all

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0

      - uses: release-drafter/release-drafter@v6
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
          publish: false
          disable-autolabeler: true

      - name: Upload Artifact
        continue-on-error: true
        uses: actions/upload-artifact@v4.3.1
        with:
          path: ./*
          name: ${{ github.event.repository.name }}.zip
          if-no-files-found: warn
          retention-days: 1
          compression-level: 6
          overwrite: true

      - name: Download Artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.event.repository.name }}.zip

      - name: Check Folder
        run: ls -a -l

      # - name: Upload Release Assets
      #   continue-on-error: true
      #   uses: softprops/action-gh-release@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     files: ./${{ github.event.repository.name }}.zip
      #     token: ${{ secrets.GITHUB_TOKEN }}
