name: Tests

on:
  pull_request:
    branches:
      - master
      - release/*
    paths-ignore:
      - "**/*.md"

jobs:
  run_tests:
    if: ${{ !(startsWith(github.head_ref, 'chore/') || startsWith(github.head_ref, 'ci/') || startsWith(github.head_ref, 'docs/')) }}
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os:
          - ubuntu-latest
        python-version:
          # - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    timeout-minutes: 20

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1
          submodules: 'recursive'

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
          pyproject-file: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          uv python pin ${{ matrix.python-version }}
          uv sync

      - name: List dependencies
        run: |
          uv pip list

      - name: Check for tests
        id: check_tests
        run: |
          if [ -f tests/test_*.py ] || [ -d tests ]; then
              echo "Tests exist, proceeding to run them."
              echo "has_tests=true" >> $GITHUB_OUTPUT
          else
              echo "No tests to run."
              echo "has_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Run pytest
        if: steps.check_tests.outputs.has_tests == 'true'
        run: |
          uv run pytest -vv
